name: Deploy Client Production

on:
  push:
    branches: [main, develop]

jobs:
  deploy_production:
    if: contains(github.ref, 'main')
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Create Env File
        run: |
          touch .env
          echo "${{ secrets.PROD_ENV }}" >> .env

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hasFiles("**/package-lock.json") }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i --force

      - name: Build
        run: CI= npm run build

      - name: Compress
        run: tar -zcvf ${{ github.sha::8 }}.tar.gz build

      - name: Upload to S3
        run: |
          aws s3 mv --region ap-northeast-2 \
          ${{ github.sha::8 }}.tar.gz \
          ${{ secrets.S3_PROD_FRONT_LOCATION }}/${{ github.sha::8 }}.tar.gz

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY_PROD }}
          script: |
            cd ~/keeper
            ./deploy_client.sh ${{ github.sha::8 }}
