version: "3.5"

services:
  app:
    container_name: app-dev
    image: keeper-homepage-app:${ENV}
    volumes:
      - ./keeper_files:/home/keeper/keeper_files
    ports:
      - 8081:8080
    command: tail -f /dev/null
    environment:
      - SECRET=${SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
    depends_on:
      - db

  db:
    container_name: db-dev
    image: keeper-homepage-db:${ENV}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3306

  nginx:
    container_name: nginx-dev
    image: keeper-homepage-nginx:${ENV}
    volumes:
      - ./docker/data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/data/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/data/nginx/ssl:/etc/letsencrypt
    ports:
      - 81:80
      - 444:443
    command: sh -c "nginx && tail -f /dev/null"
    depends_on:
      - app

  redis:
    container_name: redis-dev
    image: redis:7-alpine3.17
    ports:
      - 6380:6379
