version: "3.5"

services:
  app:
    container_name: app
    image: keeper-homepage-app:prod
    volumes:
      - keeper_files:/home/keeper/keeper_files
    ports:
      - 8080:8080
    environment:
      - SECRET=${SECRET}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - db

  db:
    container_name: db
    image: keeper-homepage-db:prod
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    container_name: redis
    image: redis:6.2
    ports:
      - 6379:6379

  nginx:
    container_name: nginx
    image: keeper-homepage-nginx:prod
    volumes:
      - docker/data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - docker/data/nginx/conf.d:/etc/nginx/conf.d
      - docker/data/client/build:/home/keeper/front
    ports:
      - 80:80
      - 443:443
    command: tail -f /dev/null

  wiki:
    container_name: wiki
    image: keeper-homepage-wiki:prod
    ports:
      - 3001:3001
